apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: aqconnecta
  labels:
    app: mariadb
spec:
  type: ClusterIP
  selector:
    app: mariadb
  ports:
    - name: mysql
      port: 3306
      targetPort: mariadb
      protocol: TCP
