apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: aqconnecta
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  serviceName: mysql
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      securityContext:
        fsGroup: 999
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: mariadb
          image: mariadb:11.4
          imagePullPolicy: IfNotPresent
          args:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: root-password
            - name: MARIADB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mariadb-config
                  key: MARIADB_DATABASE
            - name: MARIADB_USER
              valueFrom:
                configMapKeyRef:
                  name: mariadb-config
                  key: MARIADB_USER
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: user-password
          ports:
            - containerPort: 3306
              name: mariadb
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - sh
                - -lc
                - mariadb-admin ping -h 127.0.0.1 -uroot -p$MARIADB_ROOT_PASSWORD
            initialDelaySeconds: 40
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - sh
                - -lc
                - mariadb-admin ping -h 127.0.0.1 -uroot -p$MARIADB_ROOT_PASSWORD
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mariadb-pvc
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
