version: '3'
volumes:
  data:
services:
  db:
    image: mariadb:10.11
    environment:
      MYSQL_DATABASE: aqConnecta
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"