CREATE TABLE IF NOT EXISTS TB_FORMACAO_ACADEMICA
(
    ID             BINARY(36)   NOT NULL PRIMARY KEY,
    ID_UNIVERSIDADE BINARY(36)   NOT NULL,
    DESCRICAO      VARCHAR(100) NOT NULL,
    DIPLOMA        VARCHAR(255) NULL,
    DATA_INICIO    DATETIME     NOT NULL,
    DATA_FIM       DATETIME     NULL,
    ATUAL_FORMACAO BOOLEAN      NULL,
    ID_USUARIO     BINARY(36),
    CONSTRAINT fk_usuario_formacao FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID),
    CONSTRAINT fk_universidade_formacao FOREIGN KEY (ID_UNIVERSIDADE) REFERENCES TB_UNIVERSIDADE (ID)
);
