ALTER TABLE TB_USUARIO
ADD COLUMN FOTO_PERFIL VARCHAR(300);

CREATE TABLE IF NOT EXISTS RL_USUARIO_CURRICULO
(
    USUARIO_ID BINARY(36) NOT NULL,
    CURRICULO VARCHAR(300) NOT NULL,
    ID INT,
    PRIMARY KEY (ID),
    CONSTRAINT fk_usuario_curriculo FOREIGN KEY (USUARIO_ID) REFERENCES TB_USUARIO (ID)
);
