CREATE TABLE IF NOT EXISTS TB_CANDIDATURA
(
    USUARIO_ID BINARY(36) NOT NULL,
    VAGAS_ID BINARY(36) NOT NULL,
    CURRICULO_ID INT,
    CURRICULO_URL VARCHAR(300),
    ID INT auto_increment,
    PRIMARY KEY (ID),
    CONSTRAINT fk_candidatura_vagas FOREIGN KEY (VAGAS_ID) REFERENCES TB_VAGA (ID),
    CONSTRAINT fk_candidatura_usuario FOREIGN KEY (USUARIO_ID) REFERENCES TB_USUARIO (ID)
);