DROP TABLE IF EXISTS RL_EXPERIENCIA_COMPETENCIA;
DELETE FROM RL_VAGA_COMPETENCIA;
DELETE FROM RL_USUARIO_COMPETENCIA;
DELETE FROM TB_COMPETENCIA;

ALTER TABLE TB_COMPETENCIA MODIFY COLUMN DESCRICAO VARCHAR(300);