CREATE TABLE IF NOT EXISTS TB_USUARIO
(
    ID              BINARY(36)   NOT NULL PRIMARY KEY,
    NOME            VARCHAR(100) NOT NULL,
    EMAIL           VARCHAR(100) NOT NULL,
    SENHA           VARCHAR(100) NOT NULL,
    DELETADO        TINYINT(1)   NOT NULL
);

CREATE TABLE IF NOT EXISTS TB_PERFIL
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS TB_USUARIO_PERFIL
(
    ID_USUARIO BINARY(36) NOT NULL,
    ID_PERFIL INT NOT NULL,
    PRIMARY KEY (ID_USUARIO, ID_PERFIL),
    CONSTRAINT fk_usuario FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID),
    CONSTRAINT fk_perfil FOREIGN KEY (ID_PERFIL) REFERENCES TB_PERFIL (ID)
);

CREATE TABLE IF NOT EXISTS curriculum
(
    id     BINARY(36)   NOT NULL,
    userId BINARY(36)   NOT NULL,
    path   VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS post
(
    id          BINARY(36)    NOT NULL,
    userId      BINARY(36)    NOT NULL,
    name        VARCHAR(100)  NOT NULL,
    description VARCHAR(1000) NOT NULL,
    startDate   DATETIME      NOT NULL,
    endDate     DATETIME      NOT NULL
);

CREATE TABLE IF NOT EXISTS tag
(
    id   BINARY(36)  NOT NULL,
    name VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS post_has_user
(
    idPost BINARY(36) NOT NULL,
    idUser BINARY(36) NOT NULL
);


CREATE TABLE IF NOT EXISTS post_has_tag
(
    idPost BINARY(36) NOT NULL,
    idUser BINARY(36) NOT NULL
);

CREATE TABLE IF NOT EXISTS post_has_selected_user
(
    idPost BINARY(36) NOT NULL,
    idUser BINARY(36) NOT NULL
);
