CREATE TABLE IF NOT EXISTS TB_USUARIO
(
    ID              BINARY(36)   NOT NULL PRIMARY KEY,
    NOME            VARCHAR(100) NOT NULL,
    EMAIL           VARCHAR(100) NOT NULL,
    SENHA           VARCHAR(200) NOT NULL,
    DELETADO        TINYINT(1)   NOT NULL,
    ATIVADO         TINYINT(1)   NOT NULL
);

CREATE TABLE IF NOT EXISTS TB_PERMISSAO
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS RL_USUARIO_PERMISSAO
(
    ID_USUARIO BINARY(36) NOT NULL,
    ID_PERMISSAO INT NOT NULL,
    PRIMARY KEY (ID_USUARIO, ID_PERMISSAO),
    CONSTRAINT fk_usuario_perfil FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID),
    CONSTRAINT fk_permissao_usuario FOREIGN KEY (ID_PERMISSAO) REFERENCES TB_PERMISSAO (ID)
);

CREATE TABLE IF NOT EXISTS TB_CONFIRMA_TOKEN
(
    ID               BINARY(36)   NOT NULL PRIMARY KEY,
    TOKEN            VARCHAR(100),
    DATA_CRIACAO     DATETIME,
    ID_USUARIO       BINARY(36),
    CONSTRAINT fk_usuario_token FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID)
);

CREATE TABLE IF NOT EXISTS TB_EXPERIENCIA
(
    ID               BINARY(36)   NOT NULL PRIMARY KEY,
    ID_USUARIO       BINARY(36)   NOT NULL,
    TITULO           VARCHAR(50)  NOT NULL,
    INSTITUICAO      VARCHAR(70)  NOT NULL,
    DESCRICAO        VARCHAR(300) NOT NULL,
    DATA_INICIO      DATETIME     NOT NULL,
    DATA_FIM         DATETIME     NULL,
    ATUAL_EXPERIENCIA BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_usuario_experiencia FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID)
);

CREATE TABLE IF NOT EXISTS TB_COMPETENCIA
(
    ID        BINARY(36)   NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS RL_EXPERIENCIA_COMPETENCIA
(
    ID_EXPERIENCIA BINARY(36) NOT NULL,
    ID_COMPETENCIA BINARY(36) NOT NULL,
    PRIMARY KEY (ID_EXPERIENCIA, ID_COMPETENCIA),
    CONSTRAINT fk_experiencia_competencia FOREIGN KEY (ID_EXPERIENCIA) REFERENCES TB_EXPERIENCIA (ID),
    CONSTRAINT fk_competencia_experiencia FOREIGN KEY (ID_COMPETENCIA) REFERENCES TB_COMPETENCIA (ID)
);

CREATE TABLE IF NOT EXISTS TB_ENDERECO
(
    ID          BINARY(36)   NOT NULL PRIMARY KEY,
    CEP         VARCHAR(12)  NOT NULL,
    RUA         VARCHAR(100) NOT NULL,
    BAIRRO      VARCHAR(100) NOT NULL,
    CIDADE      VARCHAR(100) NOT NULL,
    ESTADO      VARCHAR(100) NOT NULL,
    PAIS        VARCHAR(100) NOT NULL,
    NUMERO_CASA INT(11)      NOT NULL,
    COMPLEMENTO VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS RL_USUARIO_ENDERECO
(
    ID_USUARIO  BINARY(36) NOT NULL,
    ID_ENDERECO BINARY(36)        NOT NULL,
    PRIMARY KEY (ID_USUARIO, ID_ENDERECO),
    CONSTRAINT fk_usuario_endereco FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID),
    CONSTRAINT fk_endereco_usuario FOREIGN KEY (ID_ENDERECO) REFERENCES TB_ENDERECO (ID)
);
