-- TTL para tokens de confirmação
ALTER TABLE TB_CONFIRMA_TOKEN ADD COLUMN DATA_EXPIRACAO TIMESTAMP NULL;

-- Soft delete padronizado: adicionar DELETADO_EM em TB_USUARIO
ALTER TABLE TB_USUARIO ADD COLUMN DELETADO_EM TIMESTAMP NULL;

-- Migrar dados existentes: se DELETADO = true, marcar DELETADO_EM como agora
UPDATE TB_USUARIO SET DELETADO_EM = NOW() WHERE DELETADO = TRUE AND DELETADO_EM IS NULL;

-- Índices para campos de busca frequente
CREATE INDEX IF NOT EXISTS IDX_USUARIO_EMAIL ON TB_USUARIO(EMAIL);
CREATE INDEX IF NOT EXISTS IDX_USUARIO_USER_URL ON TB_USUARIO(USER_URL);
CREATE INDEX IF NOT EXISTS IDX_VAGA_TITULO ON TB_VAGA(TITULO);
CREATE INDEX IF NOT EXISTS IDX_VAGA_DELETADO_EM ON TB_VAGA(DELETADO_EM);
CREATE INDEX IF NOT EXISTS IDX_CANDIDATURA_USUARIO ON TB_CANDIDATURA(USUARIO_ID);
CREATE INDEX IF NOT EXISTS IDX_CANDIDATURA_VAGA ON TB_CANDIDATURA(VAGAS_ID);
