-- Áreas temáticas de extensão (tabela de referência, semeada e gerenciável por admin)
CREATE TABLE IF NOT EXISTS TB_AREA
(
    ID        BINARY(36)   NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR(100) NOT NULL
);

INSERT INTO TB_AREA VALUES (UUID(), 'Comunicação');
INSERT INTO TB_AREA VALUES (UUID(), 'Cultura');
INSERT INTO TB_AREA VALUES (UUID(), 'Direitos Humanos e Justiça');
INSERT INTO TB_AREA VALUES (UUID(), 'Educação');
INSERT INTO TB_AREA VALUES (UUID(), 'Meio Ambiente');
INSERT INTO TB_AREA VALUES (UUID(), 'Saúde');
INSERT INTO TB_AREA VALUES (UUID(), 'Tecnologia e Produção');
INSERT INTO TB_AREA VALUES (UUID(), 'Trabalho');

-- Projeto de extensão
CREATE TABLE IF NOT EXISTS TB_PROJETO
(
    ID            BINARY(36)   NOT NULL PRIMARY KEY,
    TITULO        VARCHAR(150) NOT NULL,
    DESCRICAO     TEXT         NULL,
    ID_AREA       BINARY(36)   NULL,
    STATUS        VARCHAR(20)  NOT NULL,
    VISIBILIDADE  VARCHAR(20)  NOT NULL,
    IMAGEM_CAPA   VARCHAR(300) NULL,
    ID_DONO       BINARY(36)   NOT NULL,
    CRIADO_EM     DATETIME     NULL,
    ATUALIZADO_EM DATETIME     NULL,
    DELETADO_EM   DATETIME     NULL,
    CONSTRAINT fk_projeto_area FOREIGN KEY (ID_AREA) REFERENCES TB_AREA (ID),
    CONSTRAINT fk_projeto_dono FOREIGN KEY (ID_DONO) REFERENCES TB_USUARIO (ID)
);

-- Imagens adicionais (galeria) do projeto
CREATE TABLE IF NOT EXISTS TB_PROJETO_IMAGEM
(
    ID         BINARY(36)   NOT NULL PRIMARY KEY,
    ID_PROJETO BINARY(36)   NOT NULL,
    CAMINHO    VARCHAR(300) NOT NULL,
    ORDEM      INT          NOT NULL DEFAULT 0,
    CRIADO_EM  DATETIME     NULL,
    CONSTRAINT fk_projeto_imagem_projeto FOREIGN KEY (ID_PROJETO) REFERENCES TB_PROJETO (ID)
);

-- Membros (colaboradores) do projeto, com histórico de participação
CREATE TABLE IF NOT EXISTS TB_PROJETO_MEMBRO
(
    ID           BINARY(36)  NOT NULL PRIMARY KEY,
    ID_PROJETO   BINARY(36)  NOT NULL,
    ID_USUARIO   BINARY(36)  NOT NULL,
    PAPEL        VARCHAR(20) NOT NULL,
    ATIVO        TINYINT(1)  NOT NULL DEFAULT 1,
    DATA_ENTRADA DATETIME    NULL,
    DATA_SAIDA   DATETIME    NULL,
    CONSTRAINT fk_projeto_membro_projeto FOREIGN KEY (ID_PROJETO) REFERENCES TB_PROJETO (ID),
    CONSTRAINT fk_projeto_membro_usuario FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID)
);

CREATE INDEX IDX_PROJETO_DONO ON TB_PROJETO (ID_DONO);
CREATE INDEX IDX_PROJETO_AREA ON TB_PROJETO (ID_AREA);
CREATE INDEX IDX_PROJETO_VISIBILIDADE ON TB_PROJETO (VISIBILIDADE);
CREATE INDEX IDX_PROJETO_STATUS ON TB_PROJETO (STATUS);
CREATE INDEX IDX_PROJETO_IMAGEM_PROJETO ON TB_PROJETO_IMAGEM (ID_PROJETO);
CREATE INDEX IDX_PROJETO_MEMBRO_PROJETO ON TB_PROJETO_MEMBRO (ID_PROJETO);
CREATE INDEX IDX_PROJETO_MEMBRO_USUARIO ON TB_PROJETO_MEMBRO (ID_USUARIO);
