ALTER TABLE TB_USUARIO
    ADD CURRICULO_LATTES VARCHAR(255) NULL;

ALTER TABLE TB_USUARIO
    ADD PERFIL_GITHUB VARCHAR(255) NULL;

ALTER TABLE TB_USUARIO
    ADD PERFIL_LINKEDIN VARCHAR(255) NULL;

ALTER TABLE TB_USUARIO
    ADD TELEFONE VARCHAR(20) NULL;