CREATE TABLE IF NOT EXISTS TB_PROJETO_CONVITE
(
    ID               BINARY(36)  NOT NULL PRIMARY KEY,
    ID_PROJETO       BINARY(36)  NOT NULL,
    ID_USUARIO       BINARY(36)  NOT NULL,
    ID_CONVIDADO_POR BINARY(36)  NULL,
    PAPEL            VARCHAR(20) NOT NULL,
    STATUS           VARCHAR(20) NOT NULL,
    CRIADO_EM        DATETIME    NULL,
    RESPONDIDO_EM    DATETIME    NULL,
    CONSTRAINT fk_convite_projeto FOREIGN KEY (ID_PROJETO) REFERENCES TB_PROJETO (ID),
    CONSTRAINT fk_convite_usuario FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID),
    CONSTRAINT fk_convite_convidado_por FOREIGN KEY (ID_CONVIDADO_POR) REFERENCES TB_USUARIO (ID)
);

CREATE INDEX IDX_CONVITE_PROJETO ON TB_PROJETO_CONVITE (ID_PROJETO);
CREATE INDEX IDX_CONVITE_USUARIO ON TB_PROJETO_CONVITE (ID_USUARIO);
CREATE INDEX IDX_CONVITE_STATUS ON TB_PROJETO_CONVITE (STATUS);
