CREATE TABLE IF NOT EXISTS TB_POSTAGEM
(
    ID            BINARY(36)   NOT NULL PRIMARY KEY,
    ID_PROJETO    BINARY(36)   NOT NULL,
    ID_AUTOR      BINARY(36)   NULL,
    TITULO        VARCHAR(200) NOT NULL,
    CORPO         TEXT         NULL,
    STATUS        VARCHAR(20)  NOT NULL,
    PUBLICADO_EM  DATETIME     NULL,
    CRIADO_EM     DATETIME     NULL,
    ATUALIZADO_EM DATETIME     NULL,
    DELETADO_EM   DATETIME     NULL,
    CONSTRAINT fk_postagem_projeto FOREIGN KEY (ID_PROJETO) REFERENCES TB_PROJETO (ID),
    CONSTRAINT fk_postagem_autor FOREIGN KEY (ID_AUTOR) REFERENCES TB_USUARIO (ID)
);

CREATE TABLE IF NOT EXISTS TB_POSTAGEM_IMAGEM
(
    ID          BINARY(36)   NOT NULL PRIMARY KEY,
    ID_POSTAGEM BINARY(36)   NOT NULL,
    CAMINHO     VARCHAR(300) NOT NULL,
    ORDEM       INT          NOT NULL DEFAULT 0,
    CRIADO_EM   DATETIME     NULL,
    CONSTRAINT fk_postagem_imagem_postagem FOREIGN KEY (ID_POSTAGEM) REFERENCES TB_POSTAGEM (ID)
);

CREATE INDEX IDX_POSTAGEM_PROJETO ON TB_POSTAGEM (ID_PROJETO);
CREATE INDEX IDX_POSTAGEM_STATUS ON TB_POSTAGEM (STATUS);
CREATE INDEX IDX_POSTAGEM_PUBLICADO_EM ON TB_POSTAGEM (PUBLICADO_EM);
CREATE INDEX IDX_POSTAGEM_IMAGEM_POSTAGEM ON TB_POSTAGEM_IMAGEM (ID_POSTAGEM);
