CREATE TABLE IF NOT EXISTS TB_COMENTARIO
(
    ID                BINARY(36) NOT NULL PRIMARY KEY,
    ID_POSTAGEM       BINARY(36) NOT NULL,
    ID_AUTOR          BINARY(36) NULL,
    ID_COMENTARIO_PAI BINARY(36) NULL,
    CORPO             TEXT       NOT NULL,
    CRIADO_EM         DATETIME   NULL,
    DELETADO_EM       DATETIME   NULL,
    CONSTRAINT fk_comentario_postagem FOREIGN KEY (ID_POSTAGEM) REFERENCES TB_POSTAGEM (ID),
    CONSTRAINT fk_comentario_autor FOREIGN KEY (ID_AUTOR) REFERENCES TB_USUARIO (ID),
    CONSTRAINT fk_comentario_pai FOREIGN KEY (ID_COMENTARIO_PAI) REFERENCES TB_COMENTARIO (ID)
);

CREATE INDEX IDX_COMENTARIO_POSTAGEM ON TB_COMENTARIO (ID_POSTAGEM);
CREATE INDEX IDX_COMENTARIO_PAI ON TB_COMENTARIO (ID_COMENTARIO_PAI);
