CREATE TABLE IF NOT EXISTS TB_PROJETO_SEGUIDOR
(
    ID         BINARY(36) NOT NULL PRIMARY KEY,
    ID_PROJETO BINARY(36) NOT NULL,
    ID_USUARIO BINARY(36) NOT NULL,
    CRIADO_EM  DATETIME   NULL,
    CONSTRAINT fk_seguidor_projeto FOREIGN KEY (ID_PROJETO) REFERENCES TB_PROJETO (ID),
    CONSTRAINT fk_seguidor_usuario FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID),
    CONSTRAINT uk_seguidor_projeto_usuario UNIQUE (ID_PROJETO, ID_USUARIO)
);

CREATE INDEX IDX_SEGUIDOR_USUARIO ON TB_PROJETO_SEGUIDOR (ID_USUARIO);
