CREATE TABLE IF NOT EXISTS TB_DENUNCIA
(
    ID               BINARY(36)  NOT NULL PRIMARY KEY,
    ID_PROJETO       BINARY(36)  NOT NULL,
    ID_DENUNCIANTE   BINARY(36)  NOT NULL,
    MOTIVO           VARCHAR(30) NOT NULL,
    DESCRICAO        TEXT        NULL,
    STATUS           VARCHAR(20) NOT NULL,
    ID_RESOLVIDO_POR BINARY(36)  NULL,
    CRIADO_EM        DATETIME    NULL,
    RESOLVIDO_EM     DATETIME    NULL,
    CONSTRAINT fk_denuncia_projeto FOREIGN KEY (ID_PROJETO) REFERENCES TB_PROJETO (ID),
    CONSTRAINT fk_denuncia_denunciante FOREIGN KEY (ID_DENUNCIANTE) REFERENCES TB_USUARIO (ID),
    CONSTRAINT fk_denuncia_resolvido_por FOREIGN KEY (ID_RESOLVIDO_POR) REFERENCES TB_USUARIO (ID),
    CONSTRAINT uk_denuncia_projeto_denunciante UNIQUE (ID_PROJETO, ID_DENUNCIANTE)
);

CREATE INDEX IDX_DENUNCIA_STATUS ON TB_DENUNCIA (STATUS);
CREATE INDEX IDX_DENUNCIA_PROJETO ON TB_DENUNCIA (ID_PROJETO);
