ALTER TABLE TB_VAGA ADD COLUMN ID_PROJETO BINARY(36) NULL;
ALTER TABLE TB_VAGA ADD CONSTRAINT fk_vaga_projeto FOREIGN KEY (ID_PROJETO) REFERENCES TB_PROJETO (ID);
CREATE INDEX IDX_VAGA_PROJETO ON TB_VAGA (ID_PROJETO);

ALTER TABLE TB_PROJETO ADD COLUMN ID_UNIVERSIDADE BINARY(36) NULL;
ALTER TABLE TB_PROJETO ADD CONSTRAINT fk_projeto_universidade FOREIGN KEY (ID_UNIVERSIDADE) REFERENCES TB_UNIVERSIDADE (ID);

CREATE TABLE IF NOT EXISTS TB_PROJETO_LINK
(
    ID         BINARY(36)   NOT NULL PRIMARY KEY,
    ID_PROJETO BINARY(36)   NOT NULL,
    TITULO     VARCHAR(150) NULL,
    URL        VARCHAR(500) NOT NULL,
    ORDEM      INT          NOT NULL DEFAULT 0,
    CONSTRAINT fk_projeto_link_projeto FOREIGN KEY (ID_PROJETO) REFERENCES TB_PROJETO (ID)
);

CREATE INDEX IDX_PROJETO_LINK_PROJETO ON TB_PROJETO_LINK (ID_PROJETO);
