DROP TABLE IF EXISTS RL_USUARIO_ENDERECO;

ALTER TABLE TB_ENDERECO
    ADD COLUMN ID_USUARIO BINARY(36) NOT NULL,
    ADD CONSTRAINT fk_endereco_id_usuario FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID);