CREATE TABLE IF NOT EXISTS TB_VAGA
(
    ID            BINARY(36)   NOT NULL PRIMARY KEY,
    TITULO        VARCHAR(100) NOT NULL,
    DESCRICAO     VARCHAR(100) NOT NULL,
    LOCAL_VAGA    VARCHAR(200) NOT NULL,
    ACEITA_REMOTO TINYINT(1)   NOT NULL,
    DATA_LIMITE   DATETIME     NULL,
    CRIADO_EM     DATETIME     NULL,
    ATUALIZADO_EM DATETIME     NULL,
    DELETADO_EM   DATETIME     NULL,
    ID_USUARIO    BINARY(36),
    CONSTRAINT fk_usuario_publicador FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID)
);
