CREATE TABLE IF NOT EXISTS TB_UNIVERSIDADE
(
    ID                    BINARY(36)   NOT NULL PRIMARY KEY,
    CODIGO_DA_IES         VARCHAR(100) NOT NULL,
    NOME_DA_IES           VARCHAR(255) NOT NULL,
    SIGLA                 VARCHAR(50)  NULL,
    CATEGORIA_DA_IES      VARCHAR(25)  NULL,
    ORGANIZACAO_ACADEMICA VARCHAR(100) NULL,
    CODIGO_MUNICIPIO_IBGE VARCHAR(20)  NULL,
    MUNICIPIO             VARCHAR(100) NULL,
    UF                    VARCHAR(10)  NULL,
    SITUACAO_IES          VARCHAR(100) NULL
);


